version: "3.9"

services:
  web:
    build: .
    container_name: invoice_web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: invoice_db
    restart: always
    environment:
      DATABASE_HOSTNAME: ${DATABASE_HOSTNAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      DATABASE_PORT: ${DATABASE_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
