"""Create invoice table

Revision ID: 003
Revises: 002
Create Date: 2025-05-21 16:17:10.603666

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op  # type: ignore[attr-defined]

# revision identifiers, used by Alembic.
revision: str = "003"
down_revision: Union[str, None] = "002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invoices",
        sa.Column(
            "id",
            sa.UUID(),
            nullable=False,
            server_default=sa.text("uuid_generate_v4()"),
        ),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("client_name", sa.String(), nullable=False),
        sa.Column("client_email", sa.String(), nullable=False),
        sa.Column("street_from", sa.String(), nullable=False),
        sa.Column("street_to", sa.String(), nullable=False),
        sa.Column("city_from", sa.String(), nullable=False),
        sa.Column("city_to", sa.String(), nullable=False),
        sa.Column("postcode_from", sa.String(), nullable=False),
        sa.Column("postcode_to", sa.String(), nullable=False),
        sa.Column("country_from", sa.String(), nullable=False),
        sa.Column("country_to", sa.String(), nullable=False),
        sa.Column("invoice_date", sa.Date(), nullable=False),
        sa.Column(
            "created_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_on", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_invoices_client_email"), "invoices", ["client_email"], unique=False
    )
    op.create_index(
        op.f("ix_invoices_client_name"), "invoices", ["client_name"], unique=False
    )
    op.create_index(
        op.f("ix_invoices_country_from"), "invoices", ["country_from"], unique=False
    )
    op.create_index(
        op.f("ix_invoices_country_to"), "invoices", ["country_to"], unique=False
    )
    op.create_index(
        op.f("ix_invoices_due_date"), "invoices", ["due_date"], unique=False
    )
    op.create_index(op.f("ix_invoices_id"), "invoices", ["id"], unique=True)
    op.create_index(
        op.f("ix_invoices_invoice_date"), "invoices", ["invoice_date"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_invoices_invoice_date"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_id"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_due_date"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_country_to"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_country_from"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_client_name"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_client_email"), table_name="invoices")
    op.drop_table("invoices")
    # ### end Alembic commands ###
