"""Update to invoices table

Revision ID: 004
Revises: 003
Create Date: 2025-05-25 00:46:23.168074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '004'
down_revision: Union[str, None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE statusenum AS ENUM ('PENDING', 'PAID', 'DRAFT')");
    op.execute("CREATE TYPE paymenttermsenum AS ENUM ('ONE', 'SEVEN', 'FOURTEEN', 'THIRTY')");
    op.add_column('invoices', sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'PAID', name='statusenum'), nullable=False))
    op.add_column('invoices', sa.Column('payment_terms', sa.Enum('ONE', 'SEVEN', 'FOURTEEN', 'THIRTY', name='paymenttermsenum'), nullable=False))
    op.add_column('invoices', sa.Column('description', sa.String(), nullable=False))
    op.add_column('invoices', sa.Column('total', sa.Float(), nullable=False))
    op.alter_column('invoices', 'due_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.create_index(op.f('ix_invoices_payment_terms'), 'invoices', ['payment_terms'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_index(op.f('ix_invoices_total'), 'invoices', ['total'], unique=False)
    op.add_column('items', sa.Column('invoice_id', sa.UUID(), nullable=False))
    op.create_foreign_key("INVOICE_ITEM", 'items', 'invoices', ['invoice_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("INVOICE_ITEM", 'items', type_='foreignkey')
    op.drop_column('items', 'invoice_id')
    op.drop_index(op.f('ix_invoices_total'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_payment_terms'), table_name='invoices')
    op.alter_column('invoices', 'due_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('invoices', 'total')
    op.drop_column('invoices', 'description')
    op.drop_column('invoices', 'payment_terms')
    op.drop_column('invoices', 'status')
    op.execute("DROP TYPE statusenum")
    op.execute("DROP TYPE paymenttermsenum")
    # ### end Alembic commands ###
